### ISSUE TITLE
Breaking part of a doublechest causes an exception

### ISSUE THREAD

**Issue by Ameliorate** [CivWizardry/DungeonMod#26]
```
[02:03:28 WARN]: [DungeonMod] Task #214 for DungeonMod v2.4.2-@apiversion@ generated an exception
java.lang.IllegalArgumentException: Invalid inventory size; expected 27 or less
	at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.setContents(CraftInventory.java:83) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at pw.amel.dungeonmod.blockcopy.CopyBlock.copyBlock(CopyBlock.java:38) ~[?:?]
	at pw.amel.dungeonmod.DecayListener.lambda$handleBlockBreak$0(DecayListener.java:60) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

**Comment by Ameliorate** [comment]
This can be fixed by only trying to copy the block's half of the doublechest.
